/*
The triple (side1 =7, side2 = 24, hypotenuse =5) is generated by this formula where m = 4, and
n = 3. Write a program that takes values for m and n as input and displays the values of
Pythagorean triple.
*/
#include <iostream>
#include <cmath>

using namespace std;

int main()
{
	double m, n;

	cout << "Enter the value of m\t: ";
	cin >> m;

	cout << "Enter the value of n\t: ";
	cin >> n;

	double side1 = pow(m, 2) - pow(n, 2);
	double side2 = 2 * m * n;
	double hypotenuse = sqrt(pow(m, 2) + pow(n, 2));
	
	cout << endl;
	cout << "The side1 value is\t: " << side1 << endl;
	cout << "The side2 value is\t: " << side2 << endl;
	cout << "The hypotenuse value is\t: " << hypotenuse << endl;
	return 0;
}